# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# Linting: xclip -sel c <.github/workflows/testing.yml # https://rhysd.github.io/actionlint/

on:
  push:
    branches: [ 'trunk', 'next', 'wip/**' ]
    tags:     [ 'v[0-9]+.[0-9]+.[0-9]+*' ]
  pull_request:
    branches: ['trunk', 'next']

jobs:

  Make-Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 'Make check'
      run: |
        make check

